import = ["/home/phrimp/.config/alacritty/catppuccin/catppuccin-mocha.yml"]

[colors]

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#1c1c1c"
blue = "#77b6c5"
cyan = "#7fcab3"
green = "#9acc79"
magenta = "#a488d9"
red = "#d770af"
white = "#8d8d8d"
yellow = "#d0d26b"

[colors.primary]
background = "#000000"
foreground = "#ffffff"



[cursor.style]
shape = "Beam"

[window]
opacity = 0.75
